import type { FeatureFlagDescriptor, FeatureFlagKey, FeatureFlags } from '@/types'

const defaultFlags: FeatureFlags = {
  aiDraftAssistant: true,
  adaptiveTemplateBuilder: false,
  achievementEvidenceLocker: false,
  githubAutoProofImporter: false,
  ciCdDeploymentSync: false,
  wakatimeActivitySync: false,
  habitStreakCoach: false,
  milestoneRoadmaps: false,
  impactKpiDashboard: false,
  crossChainMirrorView: false,
  multiWalletAggregator: true,
  gasOptimizerTips: false,
  achievementBundles: false,
  liveCollaborationRooms: false,
  mentorshipMatcher: false,
  squadSprintBoard: false,
  threadedCommentsMentions: false,
  reactionPaletteMood: false,
  tipSplittingRevenueShare: false,
  rewardVaults: false,
  governanceSnapshotMirror: false,
  complianceAttestationForms: false,
  evidenceReviewWorkflows: false,
  realtimeNotificationCenter: false,
  publicWebhooksApiKeys: false,
  scheduledPublishingAutoSharing: false,
  digestEmailsPush: false,
  embeddableAchievementGallery: false,
  profileLayoutBuilder: false,
  offlineCaptureSync: false,
  onchainTimestamps: false,
  onchainVersionControl: false,
  onchainArchive: false,
  onchainPin: false,
  onchainBookmark: false,
  onchainCollection: false,
  qrCodeGeneration: false,
  embedCode: false,
  exportFormats: false,
  onchainImport: false,
  onchainBackup: false,
  onchainRestore: false,
  onchainHistory: false,
  onchainAnalytics: false,
  onchainInsights: false,
  onchainRecommendations: false,
  onchainFeed: false,
  onchainNotifications: false,
  onchainSettings: false,
  onchainAccessControl: false,
  onchainSearch: false,
  onchainFilters: false,
  onchainSorting: false,
  onchainPagination: false,
  onchainExport: false,
  onchainSharing: false,
  onchainPrint: false,
  onchainPreview: false,
  onchainValidation: false,
  onchainVerification: false,
  achievementTemplates: false,
  achievementScheduling: false,
  achievementRecurring: false,
  achievementDrafts: false,
  achievementCategories: false,
  achievementTags: false,
  achievementPrivacy: false,
  achievementVisibility: false,
  achievementExpirationManager: false,
  achievementRenewalAutomation: false,
  achievementTransferHistory: false,
  achievementOwnershipHistory: false,
  achievementCollaborationInvites: false,
  achievementCommentsModeration: false,
  achievementReactionsSystem: false,
  achievementFollowSystem: false,
  achievementShareAnalytics: false,
  achievementViewTracking: false,
  achievementEngagementMetrics: false,
  achievementPerformanceDashboard: false,
  achievementComparisonTool: false,
  achievementTrendsAnalysis: false,
  achievementCalendarView: false,
  achievementTimelineView: false,
  achievementGalleryView: false,
  achievementListView: false,
  achievementGridView: false,
  achievementDetailView: false,
  achievementQuickActions: false,
  achievementBulkOperations: false,
  achievementMetadataManagement: false,
  achievementIPFSStorage: false,
  achievementMultiChainBridge: false,
  achievementCrossChainSync: false,
  achievementGasOptimization: false,
  achievementBatchMinting: false,
  achievementMerkleTreeProofs: false,
  achievementZeroKnowledgeProofs: false,
  achievementSoulboundTokens: false,
  achievementComposability: false,
  achievementInteroperability: false,
  achievementStandardCompliance: false,
  achievementEventLogging: false,
  achievementAuditTrail: false,
  achievementComplianceReporting: false,
  achievementRiskAssessment: false,
  achievementSecurityScoring: false,
  achievementVulnerabilityScanning: false,
  achievementAccessLogging: false,
  achievementPermissionManagement: false,
  achievementRoleBasedAccess: false,
  achievementTimeBasedAccess: false,
  achievementLocationBasedAccess: false,
  achievementDeviceBasedAccess: false,
  achievementAPIRateLimiting: false,
  achievementWebhookManagement: false,
  achievementIntegrationManagement: false,
  achievementPluginSystem: false,
  achievementExtensionSystem: false,
  achievementCustomFields: false,
  achievementSmartContractEvents: false,
  achievementEventIndexing: false,
  achievementTransactionBatching: false,
  achievementGasPriceOracle: false,
  achievementTokenMetadata: false,
  achievementNFTMetadataStandard: false,
  achievementERC20Metadata: false,
  achievementTokenListings: false,
  achievementDEXRouting: false,
  achievementSlippageProtection: false,
  achievementPriceImpactCalculation: false,
  achievementLiquidityPoolAnalytics: false,
  achievementYieldCalculation: false,
  achievementAPRAPYTracking: false,
  achievementRewardDistribution: false,
  achievementStakingPoolManagement: false,
  achievementDelegationTracking: false,
  achievementValidatorOperations: false,
  achievementConsensusParticipation: false,
  achievementBlockProduction: false,
  achievementTransactionFinality: false,
  achievementCrossChainState: false,
  achievementBridgeValidators: false,
  achievementRelayerOperations: false,
  achievementOracleAggregation: false,
  achievementPriceFeeds: false,
  achievementDataFeeds: false,
  achievementRandomNumberGeneration: false,
  achievementVRF: false,
  achievementCommitRevealSchemes: false,
  achievementRunbookRegistry: false,
  achievementIncidentPlayback: false,
  achievementSequencerSLA: false,
  achievementLatencyHeatmap: false,
  operationalResilienceSuite: false,
  autonomousAssuranceSuite: false,
  achievementPostmortemVault: false,
  achievementGaslessTransactions: false,
  achievementFlashLoans: false,
  achievementFlashSwaps: false,
  achievementLimitOrders: false,
  achievementStopLossOrders: false,
  achievementDEXAggregator: false,
  achievementMEVProtection: false,
  achievementLiquidityMining: false,
  achievementStakingRewards: false,
  achievementTokenLocks: false,
  achievementTokenBurns: false,
  achievementTokenMints: false,
  achievementTokenTransfers: false,
  achievementTokenApprovals: false,
  achievementTokenSwaps: false,
  achievementPriceOracleIntegration: false,
  achievementChainlinkIntegration: false,
  achievementGraphIntegration: false,
  achievementENSDomains: false,
  achievementUnstoppableDomains: false,
  achievementTxSimulation: false,
  achievementSandwichDetector: false,
  achievementFrontRunningAlerts: false,
  achievementBlockspaceReservations: false,
  achievementBridgeFeeEstimator: false,
  achievementIntentBroadcasting: false,
  achievementBuilderSlotScheduler: false,
  achievementSessionKeysManager: false,
  achievementPaymasterPlanner: false,
  achievementSessionRevocation: false,
  attestationCircuitStudio: false,
  stakeSlashingRadar: false,
  coldStorageEscrows: false,
  recurringRoyaltyIndex: false,
  reownAgentTrail: false,
  fraudProofMonitor: false,
  incidentAutoTriage: false,
  invoiceHashVault: false,
  didSessionAnchors: false,
  executableBundleProofs: false,
  satelliteUplinkReceipts: false,
  automationCircuitBreakers: false,
  treasuryNavClaims: false,
  antiSybilDossier: false,
  schemaRegistryHashes: false,
  composabilityBlueprintIds: false,
  okrProofStreams: false,
  toolchainFingerprints: false,
  regionRoutingTables: false,
  attractorScoreEngine: false,
  dataSovereigntyLedger: false,
  redTeamExerciseLog: false,
  policyArbitrationHooks: false,
  keyCeremonyProofs: false,
  stateDiffSnapshots: false,
  latencySlaWitness: false,
  guardianRotationLog: false,
  postQuantumPreview: false,
  listenerSyncMap: false,
  jurisdictionalTriggerGates: false,
  achievementHotfixStream: false,
  achievementSafelistRegistry: false,
  achievementStressTest: false,
  achievementAdaptiveEscrowTrees: false,
  achievementAttestationRelayMesh: false,
  achievementSovereignWorkspaceClones: false,
  achievementMultiTenantKpiMap: false,
  achievementParameterGuardrails: false,
  achievementEvidenceDiffVisualizer: false,
  achievementIntegrityBackfillEngine: false,
  achievementCrossDomainIntentRouter: false,
  achievementRecoveryGuardianCouncil: false,
  achievementDeterministicBatchReactor: false,
  achievementZkKpiOracle: false,
  achievementLiquidBacklogUnderwriter: false,
  achievementRewardCliffSimulator: false,
  achievementGovernanceHeartbeatMonitor: false,
  achievementStreakAnchorVaults: false,
  achievementCensorshipEscapeHatch: false,
  achievementImpactWeightNotary: false,
  achievementDelegatedWitnessSwarms: false,
  achievementTreasuryDriftSentinel: false,
  achievementProgrammaticBonusStreams: false,
  achievementEthicsDisclosureLedger: false,
  achievementAutoprunedEvidenceTrees: false,
  achievementFailureModeSandbox: false,
  achievementSlaEscrowMonitor: false,
  achievementReentryTimelockGuard: false,
  achievementOmnichainInboxRouter: false,
  achievementAdaptiveReputationBonds: false,
  achievementSentinelConsensusMirror: false,
  achievementPredictiveFailoverGraph: false,
  achievementIntentDelayVault: false,
  achievementGuardianBondEscrow: false,
  achievementCustodyChainSequencer: false,
  achievementEncryptionEnvelopeLedger: false,
  achievementDeviceTrustFabric: false,
  achievementRateLimitBeacon: false,
  achievementPostQuantumAttestor: false,
  achievementRollingProofContinuity: false,
  achievementRollforwardRepairKit: false,
  achievementMultihopRewardDirector: false,
  achievementGasRefundRouter: false,
  achievementSovereignExecutorLedger: false,
  achievementGuardianDriftRadar: false,
  achievementIntegrityBeaconSwitchboard: false,
  achievementAuditReplayShuttle: false,
  achievementEvidenceCompressionLab: false,
  achievementReviewerSignalToken: false,
  achievementBridgeTimeoutEscrow: false,
  achievementUnlockConditionGraph: false,
  achievementExecutionCircuitNotebook: false,
  achievementMempoolMirrorChain: false,
  achievementMultipartyDustSettlement: false,
  achievementVaultWarmupScheduler: false,
  achievementConfigLintOracle: false,
  achievementCarbonImpactProofset: false,
  achievementAdaptiveRecoveryTree: false,
  achievementWarrantCanaryRegister: false,
  achievementPrivacyEnvelopeSwitch: false,
  achievementLatencyInsuranceVaults: false,
  achievementDynamicRiskOracles: false,
  achievementCrossChainQuorumSync: false,
  achievementPredictiveOpsEscalations: false,
  achievementAttestationRevalidationLoop: false,
  achievementDataResidencyShields: false,
  achievementCompliantBridgingEscrows: false,
  achievementMultiSigHeartbeatLogger: false,
  achievementKeeperFallbackRegistry: false,
  achievementChainHandoffPlaybooks: false,
  achievementTimewarpAuditTrail: false,
  achievementTermSheetAnchors: false,
  achievementRetroFundingRouters: false,
  achievementOnchainQaQueues: false,
  achievementServiceGraphMapper: false,
  achievementDeterministicCompressionForge: false,
  achievementTreasuryStressMap: false,
  achievementRewardEmissionGovernors: false,
  achievementSustainableMiningOffsets: false,
  achievementEmergencyGasSwitchboard: false,
  achievementHandoverEscrowKeys: false,
  achievementCredentialSanityScanner: false,
  achievementIntentFailureRegistry: false,
  achievementProgressiveDisclosureFlows: false,
  achievementKpiConfidenceBands: false,
  achievementLiquidityFallbackLines: false,
  achievementOperatorEscrowBonds: false,
  achievementValidatorReliefSignals: false,
  achievementImpactAuditTrails: false,
  achievementZeroDayResponseLedger: false,
  achievementReownSessionSentinel: false,
  achievementOmniwalletDelegationFabric: false,
  achievementPerimeterAccessLedger: false,
  achievementIncentiveHedgingVault: false,
  achievementSettlementRaceArbiter: false,
  achievementImpactStreamingRouter: false,
  achievementSovereignRollupSnapshot: false,
  achievementIntentCarbonCreditsRouter: false,
  achievementComplianceAutoCurator: false,
  achievementRealtimeRetroScoreboard: false,
  achievementAdaptiveRoyaltyVaults: false,
  achievementCrossDaoEscrowNetting: false,
  achievementMultiHopVerificationTrees: false,
  achievementTemporalEvidenceLineage: false,
  achievementSettlementAssurancePools: false,
  achievementMultiDomainChainLocks: false,
  achievementRollupSafetyNet: false,
  achievementVerifiedSimulationTrails: false,
  achievementAttestationUpgradeCouncil: false,
  achievementBudgetPressureGauge: false,
  achievementAutonomicXpCurves: false,
  achievementTokenizedPlaybookMarket: false,
  achievementSovereignAccessGraph: false,
  achievementAdaptiveRateLimiter: false,
  achievementKeeperMarketMaker: false,
  achievementAutoRenewalBonds: false,
  achievementDisputeHeatIndex: false,
  achievementGovernanceHandoffCapsule: false,
  achievementAiFactCheckAttestor: false,
  achievementImpactOptionVaults: false,
  achievementContinuityChaosGuard: false,
  achievementIntentHedgingPools: false,
  achievementMultiAgentIncidentMesh: false,
  achievementTemporalRollbackPermits: false,
  achievementProbabilisticFailureForecaster: false,
  achievementReownSessionCircuit: false,
  achievementCounterpartyEscalationBonds: false,
  achievementDistributedCustodyVaults: false,
  achievementAutonomousPatchCaravan: false,
  achievementTreasuryHeartbeatOrchestrator: false,
  achievementSettlementFinalityRadar: false,
  achievementDisasterAidEscrowGrid: false,
  achievementComplianceEvidenceRouter: false,
  achievementMultiChainDebriefStudio: false,
  achievementWitnessDensityTracker: false,
  achievementStagedRedemptionQueue: false,
  achievementQuantumReadinessRegistry: false,
  achievementSovereignDataRelay: false,
  achievementRegenerativeBudgetVault: false,
  achievementAdaptiveScopeGuard: false,
  achievementMultiHopTicketingGraph: false,
  achievementOperatorCredentialVault: false,
  achievementResilienceKpiSynthesizer: false,
  achievementOmniAlertCoordinator: false,
  achievementHazardInsuranceGrid: false,
  achievementStatefulCircuitBackups: false,
  achievementRapidNeutralizationSwitch: false,
  achievementRecoveryRoleRandomizer: false,
  achievementCustodialIntegrityGrid: false,
  achievementEvidenceEscrowExchange: false,
  achievementContinuityAtlas: false,
  achievementIntentQuarantineFabric: false,
  achievementGuardianWageEscrow: false,
  achievementContractorIntegrityGraph: false,
  achievementTelemetryInoculationLab: false,
  achievementSovereignFailoverLoom: false,
  achievementLivingSlaCovenant: false,
  achievementObservabilitySignalMint: false,
  achievementAutonomousLifelineBrigade: false,
  achievementSnapshotIntegrityGyre: false,
  achievementServiceRebateRouter: false,
  achievementCongestionEscalationBoard: false,
  achievementMultidimensionalRiskRadar: false,
  achievementReliefBondSyndicator: false,
  achievementTroubleshootingWitnessTree: false,
  achievementBlackstartDrillLedger: false,
  achievementCrossAxisResponseMesh: false,
  achievementEvidenceRedactionSanctuary: false,
  achievementProvincialFallbackFederation: false,
  achievementGovernanceResonanceHarmonizer: false,
  achievementKpiDampenerOracle: false,
  achievementCushionLiquidityRouter: false,
  achievementImpactRelayTwin: false,
  achievementQuietHourSentinel: false,
  achievementEmpathyPulseGraph: false,
  achievementMutualAidClearinghouse: false,
  achievementComplianceScenarioForge: false,
  achievementFailoverCreditExchange: false,
  achievementProgressiveMintThrottle: false,
  achievementSovereignPolicyManuscript: false,
  achievementLighthouseRiskSonar: false,
  achievementContinuityBufferPools: false,
  achievementIntentBackflowScrubber: false,
  achievementIncidentSemaphoreGrid: false,
  achievementSovereignWarmPathRouter: false,
  achievementReownRelaySafeguards: false,
  achievementDeltaAbortSwitch: false,
  achievementCrisisThresholdTuner: false,
  achievementFailureMemoryLedger: false,
  achievementAutonomousRelayContracts: false,
  achievementCustodianSyncOrchestra: false,
  achievementProofShelterPools: false,
  achievementSafetyNetEscrowHub: false,
  achievementMultistakeWitnessCloud: false,
  achievementResilienceCreditNotary: false,
  achievementTelemetryDriftVault: false,
  achievementErrorBudgetNotifier: false,
  achievementRedlineCalibrationBureau: false,
  achievementSovereignRollbackTheater: false,
  achievementMissionReplayCapsule: false,
  achievementCrossDomainLifelineBridge: false,
  achievementSafeguardOperatorGraph: false,
  achievementObsolescenceAlarmGrid: false,
  achievementGuardianReliefQueue: false,
  achievementAnomalySwarmDispatcher: false,
  achievementIncidentTreatyLedger: false,
  achievementCircuitSanityMirror: false,
  achievementImpactCushionOracle: false,
  achievementContinuityPolicyStudio: false,
  achievementNightwatchSilenceTimer: false,
  achievementIntentBlueprintRegistry: false,
  achievementProofSequencerCoop: false,
  achievementTreasuryWeatherDesk: false,
  achievementImpactFuturesClearinghouse: false,
  achievementAdaptiveValidatorConcierge: false,
  achievementAutonomousGrantsRouter: false,
  achievementCrossDomainSandboxHarness: false,
  achievementCoordinationCanvas: false,
  achievementAiPairingLedger: false,
  achievementOnchainStandupChronicle: false,
  achievementPursuitBatchOptimizer: false,
  achievementIntentCollateralComposer: false,
  achievementExecutionWeatherStation: false,
  achievementRiskLayeredTreasuryLadder: false,
  achievementModularArbitrationEscrow: false,
  achievementGradientBonusOptions: false,
  achievementCarbonSwapboard: false,
  achievementSovereignTaskMesh: false,
  achievementDeviceBloomFilter: false,
  achievementSponsorshipExchange: false,
  achievementGovernanceMemoryVault: false,
  achievementAutoVerifierPipeline: false,
  achievementMentorshipTrailLedger: false,
  achievementZeroLatencySyncRelay: false,
  achievementMultiscopePaymasterOrchestrator: false,
  achievementProofLiquidityMarketplace: false,
  achievementPolicyDriftSentinel: false,
  achievementImpactDividendRouter: false,
  achievementIntentRecoveryForge: false,
  achievementBuilderAvailabilityIndex: false,
  // Helios Mesh wave feature flags
  achievementHeliosBeaconOrchestrator: false,
  achievementIncidentSwarmSandbox: false,
  achievementBlastproofCommandQueue: false,
  achievementRunbookDeltaCodex: false,
  achievementResponderBondEscrow: false,
  achievementAutopsyContinuityLoom: false,
  achievementTelemetryParityLatch: false,
  achievementCrisisFloatPoolRouter: false,
  achievementGuardianReachRouter: false,
  achievementLatencyFuseConsole: false,
  achievementRebuildDryRunCapsule: false,
  achievementChainAirgapSwitch: false,
  achievementEvidenceCourierSpoke: false,
  achievementPatchRelayLocker: false,
  achievementCredentialBurnVault: false,
  achievementAlertIntegrityGate: false,
  achievementResponseTempoLedger: false,
  achievementOperatorReliefWheel: false,
  achievementVictimReliefCoordinator: false,
  achievementRegionHopBlueprint: false,
  achievementConfigFreezeHatch: false,
  achievementForensicAnchorBeacon: false,
  achievementIncidentInsightWeave: false,
  achievementProofRefugeBridge: false,
  achievementContinuityDriftScope: false,
  achievementRecoveryCompassGauge: false,
  achievementIncidentDebtLedger: false,
  achievementQuietPhaseBroadcaster: false,
  achievementAutothrottleGuardian: false,
  achievementGuardianCareConsole: false,
  // Aurora Wave feature flags
  achievementEigenRestakeShield: false,
  achievementIntentSequencerGuard: false,
  achievementMevAmnestyEscrow: false,
  achievementSlotCommitmentLedger: false,
  achievementL2SettlementMirror: false,
  achievementAccountAbstractionCircuit: false,
  achievementDeterministicPreconfirmVaults: false,
  achievementIntentBatonRelay: false,
  achievementGuardianRagequitPool: false,
  achievementOperatorSlippageSentinel: false,
  achievementCrossRollupWitnessHub: false,
  achievementDeterministicGasOracle: false,
  achievementPartialWithdrawalRouter: false,
  achievementSovereignRpcQuorum: false,
  achievementZksyncStateSyncer: false,
  achievementIntentMerkleJournal: false,
  achievementDeadlineArbitrationBridge: false,
  achievementMultiAssetProofRouter: false,
  achievementVerificationCreditLedger: false,
  achievementGuardianVaultTimelock: false,
  achievementExecutionCapsule: false,
  achievementRiskWeightedVaultMatrix: false,
  achievementAssetTraceMatrix: false,
  achievementComplianceAnchorChain: false,
  achievementOffchainEvidenceHashline: false,
  achievementGuardianMultisigAssembler: false,
  achievementIntentSuspensionSwitch: false,
  achievementResilienceScoreBeacon: false,
  achievementPayoutCircuitBreaker: false,
  achievementDataAvailabilityVault: false,
}

export const auroraWaveFlagMetadata: FeatureFlagDescriptor[] = [
  {
    key: 'achievementEigenRestakeShield',
    title: 'Achievement EigenRestake Shield',
    summary: 'Pins EigenLayer restake attestations per achievement with slashable stakes for non-compliance.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementIntentSequencerGuard',
    title: 'Achievement Intent Sequencer Guard',
    summary: 'Enforces deterministic sequencing receipts for bundled intents using slot and block anchors.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementMevAmnestyEscrow',
    title: 'Achievement MEV Amnesty Escrow',
    summary: 'Escrows MEV restitution liquidity until affected achievements countersign payout receipts.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementSlotCommitmentLedger',
    title: 'Achievement Slot Commitment Ledger',
    summary: 'Logs validator slot commitments so reviewers can trace finality windows per milestone.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementL2SettlementMirror',
    title: 'Achievement L2 Settlement Mirror',
    summary: 'Mirrors Optimism/Base/Arbitrum settlement proofs and challenge receipts before unlocks fire.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementAccountAbstractionCircuit',
    title: 'Achievement Account-Abstraction Circuit',
    summary: 'Stores ERC-4337 session scopes, policy hashes, and paymaster attestations for automation wallets.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementDeterministicPreconfirmVaults',
    title: 'Achievement Deterministic Pre-Confirm Vaults',
    summary: 'Captures pre-confirm signatures, expiries, and fallback intents for deterministic delivery.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementIntentBatonRelay',
    title: 'Achievement Intent Baton Relay',
    summary: 'Relays intents between squads with notarized baton metadata and SLA-backed acknowledgements.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementGuardianRagequitPool',
    title: 'Achievement Guardian Ragequit Pool',
    summary: 'Bonds guardian capital and enforces ragequit exits that require attested replacements.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementOperatorSlippageSentinel',
    title: 'Achievement Operator Slippage Sentinel',
    summary: 'Tracks operator-led swaps against declared slippage ceilings and emits breach attestations.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementCrossRollupWitnessHub',
    title: 'Achievement Cross-Rollup Witness Hub',
    summary: 'Registers witness quorum proofs across rollups and settlement layers for continuity.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementDeterministicGasOracle',
    title: 'Achievement Deterministic Gas Oracle',
    summary: 'Snaps gas oracle readings, variance envelopes, and reviewer approvals per proof submission.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementPartialWithdrawalRouter',
    title: 'Achievement Partial Withdrawal Router',
    summary: 'Routes partial treasury withdrawals with multi-epoch attestation trails and unlock checkpoints.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementSovereignRpcQuorum',
    title: 'Achievement Sovereign RPC Quorum',
    summary: 'Records quorum-approved RPC endpoints, heartbeat intervals, and failover receipts per scope.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementZksyncStateSyncer',
    title: 'Achievement zkSync State Syncer',
    summary: 'Anchors zkSync state root proofs aligned to BuilderProof checkpoints and batch IDs.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementIntentMerkleJournal',
    title: 'Achievement Intent Merkle Journal',
    summary: 'Maintains rolling Merkle journals of intents plus evidence metadata for quick audits.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementDeadlineArbitrationBridge',
    title: 'Achievement Deadline Arbitration Bridge',
    summary: 'Encodes arbitration workflows and quorum verdict hashes when deadlines slip.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementMultiAssetProofRouter',
    title: 'Achievement Multi-Asset Proof Router',
    summary: 'Maps ERC-20/721/1155 asset proofs with settlement policy metadata and release logs.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementVerificationCreditLedger',
    title: 'Achievement Verification Credit Ledger',
    summary: 'Tracks verifier credits burned per achievement to meter scarce audit resources.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementGuardianVaultTimelock',
    title: 'Achievement Guardian Vault Timelock',
    summary: 'Enforces guardian-managed timelocks before sensitive contract paths mutate state.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementExecutionCapsule',
    title: 'Achievement Execution Capsule',
    summary: 'Packages deterministic execution capsules with calldata hashes and replay guards.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementRiskWeightedVaultMatrix',
    title: 'Achievement Risk-Weighted Vault Matrix',
    summary: 'Scores vault exposures per achievement and links mitigation actions plus approvals.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementAssetTraceMatrix',
    title: 'Achievement Asset Trace Matrix',
    summary: 'Traces asset provenance hops with hashed receipts for treasury transparency.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementComplianceAnchorChain',
    title: 'Achievement Compliance Anchor Chain',
    summary: 'Chains compliance attestations (KYC/KYB) with revocation proofs and jurisdiction tags.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementOffchainEvidenceHashline',
    title: 'Achievement Offchain Evidence Hashline',
    summary: 'Anchors offchain bundle hashes with verifier signatures and expiry timers.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementGuardianMultisigAssembler',
    title: 'Achievement Guardian Multisig Assembler',
    summary: 'Registers guardian multisig compositions, rotations, and quorum drift monitors.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementIntentSuspensionSwitch',
    title: 'Achievement Intent Suspension Switch',
    summary: 'Lets reviewers halt automation flows until governance re-enables them.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementResilienceScoreBeacon',
    title: 'Achievement Resilience Score Beacon',
    summary: 'Publishes resilience score oracles sourced from telemetry feeds with refresh proofs.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementPayoutCircuitBreaker',
    title: 'Achievement Payout Circuit Breaker',
    summary: 'Auto-pauses payouts beyond policy thresholds until guardian quorum restarts flow.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
  {
    key: 'achievementDataAvailabilityVault',
    title: 'Achievement Data Availability Vault',
    summary: 'Commits data-availability proofs (blob/celestia) tying external data to achievements.',
    docPath: '/docs/onchain-feature-expansion.md#aurora-wave--ethereum-control-plane',
    wave: 'Aurora Wave',
  },
]

export const aegisWaveFlagMetadata: FeatureFlagDescriptor[] = [
  {
    key: 'achievementContinuityAtlas',
    title: 'Achievement Continuity Atlas',
    summary: 'Captures reconciler hashes and drift envelopes so ledgers can prove eventual consistency.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementIntentQuarantineFabric',
    title: 'Achievement Intent Quarantine Fabric',
    summary: 'Isolates risky intents with notarized mitigation plans and unlock quorums.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementGuardianWageEscrow',
    title: 'Achievement Guardian Wage Escrow',
    summary: 'Binds guardian compensation to attested duties via programmable escrows.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementContractorIntegrityGraph',
    title: 'Achievement Contractor Integrity Graph',
    summary: 'Graphs contractor deliverables, proofs, and escalation paths for vendor trust.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementTelemetryInoculationLab',
    title: 'Achievement Telemetry Inoculation Lab',
    summary: 'Runs dataset inoculation recipes before telemetry hits production metrics.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementSovereignFailoverLoom',
    title: 'Achievement Sovereign Failover Loom',
    summary: 'Weaves deterministic failover lanes with health probes for sovereign deployments.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementLivingSlaCovenant',
    title: 'Achievement Living SLA Covenant',
    summary: 'Publishes evolving SLA pledges with enforcement windows and penalty classes.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementObservabilitySignalMint',
    title: 'Achievement Observability Signal Mint',
    summary: 'Mints coverage attestations proving logs/metrics/traces met policy thresholds.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementAutonomousLifelineBrigade',
    title: 'Achievement Autonomous Lifeline Brigade',
    summary: 'Registers emergency automation agents with fingerprints and expiries.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementSnapshotIntegrityGyre',
    title: 'Achievement Snapshot Integrity Gyre',
    summary: 'Rotates multi-plane snapshot manifests with checksum proofs for recovery.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementServiceRebateRouter',
    title: 'Achievement Service Rebate Router',
    summary: 'Routes make-good credits to builders whenever SLA trigger signals trip.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementCongestionEscalationBoard',
    title: 'Achievement Congestion Escalation Board',
    summary: 'Publishes severity-ranked boards so automation respects congestion priorities.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementMultidimensionalRiskRadar',
    title: 'Achievement Multi-Dimensional Risk Radar',
    summary: 'Aggregates weighted risk axes and reviewer overrides for rapid audits.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementReliefBondSyndicator',
    title: 'Achievement Relief Bond Syndicator',
    summary: 'Parameterizes relief bonds that unlock liquidity when metrics breach.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementTroubleshootingWitnessTree',
    title: 'Achievement Troubleshooting Witness Tree',
    summary: 'Stores reviewer-signed troubleshooting trees with deterministic paths.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementBlackstartDrillLedger',
    title: 'Achievement Blackstart Drill Ledger',
    summary: 'Notarizes blackstart drill cadences, participants, and outcomes.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementCrossAxisResponseMesh',
    title: 'Achievement Cross-Axis Response Mesh',
    summary: 'Maps response clusters, acknowledgement proofs, and escalation paths.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementEvidenceRedactionSanctuary',
    title: 'Achievement Evidence Redaction Sanctuary',
    summary: 'Protects redacted artifacts with reviewer approvals and sealed hashes.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementProvincialFallbackFederation',
    title: 'Achievement Provincial Fallback Federation',
    summary: 'Registers regional failover federations with readiness attestations.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementGovernanceResonanceHarmonizer',
    title: 'Achievement Governance Resonance Harmonizer',
    summary: 'Aligns overlapping governance feeds, quorum thresholds, and arbitration logic.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementKpiDampenerOracle',
    title: 'Achievement KPI Dampener Oracle',
    summary: 'Publishes smoothed KPI curves next to raw metrics to contextualize volatility.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementCushionLiquidityRouter',
    title: 'Achievement Cushion Liquidity Router',
    summary: 'Routes treasury cushion pools to stressed achievements with transparent triggers.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementImpactRelayTwin',
    title: 'Achievement Impact Relay Twin',
    summary: 'Mirrors upstream/downstream telemetry feeds with checksum proofs.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementQuietHourSentinel',
    title: 'Achievement Quiet Hour Sentinel',
    summary: 'Enforces quiet-hour windows with override approvals and impacted scopes.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementEmpathyPulseGraph',
    title: 'Achievement Empathy Pulse Graph',
    summary: 'Aggregates anonymized wellbeing signals to expose burnout risk.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementMutualAidClearinghouse',
    title: 'Achievement Mutual Aid Clearinghouse',
    summary: 'Coordinates DAO resource pledges, unlock triggers, and repayment rules.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementComplianceScenarioForge',
    title: 'Achievement Compliance Scenario Forge',
    summary: 'Runs regulator-facing scenario verdicts with signed reviewer proofs.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementFailoverCreditExchange',
    title: 'Achievement Failover Credit Exchange',
    summary: 'Matches failover providers to escrowed credits and SLA metadata.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementProgressiveMintThrottle',
    title: 'Achievement Progressive Mint Throttle',
    summary: 'Gates high-risk mints behind checkpoint sequences and throughput curves.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
  {
    key: 'achievementSovereignPolicyManuscript',
    title: 'Achievement Sovereign Policy Manuscript',
    summary: 'Versions sovereign policy packs with approvers, jurisdictions, and revocations.',
    docPath: '/docs/onchain-feature-expansion.md#aegis-matrix--resilience-catalysts',
    wave: 'Aegis Matrix',
  },
]

let flagOverrides: Partial<FeatureFlags> = {}

export const configureFeatureFlags = (overrides: Partial<FeatureFlags>) => {
  flagOverrides = { ...flagOverrides, ...overrides }
}

export const getFeatureFlags = (): FeatureFlags => ({
  ...defaultFlags,
  ...flagOverrides,
})

export const isFeatureEnabled = (flag: FeatureFlagKey) => {
  const flags = getFeatureFlags()
  return !!flags[flag]
}



