import type { FeatureFlagKey, FeatureFlags } from '@/types'

const defaultFlags: FeatureFlags = {
  aiDraftAssistant: true,
  adaptiveTemplateBuilder: false,
  achievementEvidenceLocker: false,
  githubAutoProofImporter: false,
  ciCdDeploymentSync: false,
  wakatimeActivitySync: false,
  habitStreakCoach: false,
  milestoneRoadmaps: false,
  impactKpiDashboard: false,
  crossChainMirrorView: false,
  multiWalletAggregator: true,
  gasOptimizerTips: false,
  achievementBundles: false,
  liveCollaborationRooms: false,
  mentorshipMatcher: false,
  squadSprintBoard: false,
  threadedCommentsMentions: false,
  reactionPaletteMood: false,
  tipSplittingRevenueShare: false,
  rewardVaults: false,
  governanceSnapshotMirror: false,
  complianceAttestationForms: false,
  evidenceReviewWorkflows: false,
  realtimeNotificationCenter: false,
  publicWebhooksApiKeys: false,
  scheduledPublishingAutoSharing: false,
  digestEmailsPush: false,
  embeddableAchievementGallery: false,
  profileLayoutBuilder: false,
  offlineCaptureSync: false,
  onchainTimestamps: false,
  onchainVersionControl: false,
  onchainArchive: false,
  onchainPin: false,
  onchainBookmark: false,
  onchainCollection: false,
  qrCodeGeneration: false,
  embedCode: false,
  exportFormats: false,
  onchainImport: false,
  onchainBackup: false,
  onchainRestore: false,
  onchainHistory: false,
  onchainAnalytics: false,
  onchainInsights: false,
  onchainRecommendations: false,
  onchainFeed: false,
  onchainNotifications: false,
  onchainSettings: false,
  onchainAccessControl: false,
  onchainSearch: false,
  onchainFilters: false,
  onchainSorting: false,
  onchainPagination: false,
  onchainExport: false,
  onchainSharing: false,
  onchainPrint: false,
  onchainPreview: false,
  onchainValidation: false,
  onchainVerification: false,
  achievementTemplates: false,
  achievementScheduling: false,
  achievementRecurring: false,
  achievementDrafts: false,
  achievementCategories: false,
  achievementTags: false,
  achievementPrivacy: false,
  achievementVisibility: false,
  achievementExpirationManager: false,
  achievementRenewalAutomation: false,
  achievementTransferHistory: false,
  achievementOwnershipHistory: false,
  achievementCollaborationInvites: false,
  achievementCommentsModeration: false,
  achievementReactionsSystem: false,
  achievementFollowSystem: false,
  achievementShareAnalytics: false,
  achievementViewTracking: false,
  achievementEngagementMetrics: false,
  achievementPerformanceDashboard: false,
  achievementComparisonTool: false,
  achievementTrendsAnalysis: false,
  achievementCalendarView: false,
  achievementTimelineView: false,
  achievementGalleryView: false,
  achievementListView: false,
  achievementGridView: false,
  achievementDetailView: false,
  achievementQuickActions: false,
  achievementBulkOperations: false,
  achievementMetadataManagement: false,
  achievementIPFSStorage: false,
  achievementMultiChainBridge: false,
  achievementCrossChainSync: false,
  achievementGasOptimization: false,
  achievementBatchMinting: false,
  achievementMerkleTreeProofs: false,
  achievementZeroKnowledgeProofs: false,
  achievementSoulboundTokens: false,
  achievementComposability: false,
  achievementInteroperability: false,
  achievementStandardCompliance: false,
  achievementEventLogging: false,
  achievementAuditTrail: false,
  achievementComplianceReporting: false,
  achievementRiskAssessment: false,
  achievementSecurityScoring: false,
  achievementVulnerabilityScanning: false,
  achievementAccessLogging: false,
  achievementPermissionManagement: false,
  achievementRoleBasedAccess: false,
  achievementTimeBasedAccess: false,
  achievementLocationBasedAccess: false,
  achievementDeviceBasedAccess: false,
  achievementAPIRateLimiting: false,
  achievementWebhookManagement: false,
  achievementIntegrationManagement: false,
  achievementPluginSystem: false,
  achievementExtensionSystem: false,
  achievementCustomFields: false,
  achievementSmartContractEvents: false,
  achievementEventIndexing: false,
  achievementTransactionBatching: false,
  achievementGasPriceOracle: false,
  achievementTokenMetadata: false,
  achievementNFTMetadataStandard: false,
  achievementERC20Metadata: false,
  achievementTokenListings: false,
  achievementDEXRouting: false,
  achievementSlippageProtection: false,
  achievementPriceImpactCalculation: false,
  achievementLiquidityPoolAnalytics: false,
  achievementYieldCalculation: false,
  achievementAPRAPYTracking: false,
  achievementRewardDistribution: false,
  achievementStakingPoolManagement: false,
  achievementDelegationTracking: false,
  achievementValidatorOperations: false,
  achievementConsensusParticipation: false,
  achievementBlockProduction: false,
  achievementTransactionFinality: false,
  achievementCrossChainState: false,
  achievementBridgeValidators: false,
  achievementRelayerOperations: false,
  achievementOracleAggregation: false,
  achievementPriceFeeds: false,
  achievementDataFeeds: false,
  achievementRandomNumberGeneration: false,
  achievementVRF: false,
  achievementCommitRevealSchemes: false,
  achievementRunbookRegistry: false,
  achievementIncidentPlayback: false,
  achievementSequencerSLA: false,
  achievementLatencyHeatmap: false,
  operationalResilienceSuite: false,
  autonomousAssuranceSuite: false,
  achievementPostmortemVault: false,
}

let flagOverrides: Partial<FeatureFlags> = {}

export const configureFeatureFlags = (overrides: Partial<FeatureFlags>) => {
  flagOverrides = { ...flagOverrides, ...overrides }
}

export const getFeatureFlags = (): FeatureFlags => ({
  ...defaultFlags,
  ...flagOverrides,
})

export const isFeatureEnabled = (flag: FeatureFlagKey) => {
  const flags = getFeatureFlags()
  return !!flags[flag]
}



